export * from './accountResource.service';
import { AccountResourceService } from './accountResource.service';
export * from './appraisalControllerResource.service';
import { AppraisalControllerResourceService } from './appraisalControllerResource.service';
export * from './appraisalResource.service';
import { AppraisalResourceService } from './appraisalResource.service';
export * from './gitResource.service';
import { GitResourceService } from './gitResource.service';
export * from './hackathonResource.service';
import { HackathonResourceService } from './hackathonResource.service';
export * from './jiraResource.service';
import { JiraResourceService } from './jiraResource.service';
export * from './lateArrivalResource.service';
import { LateArrivalResourceService } from './lateArrivalResource.service';
export * from './leaveResource.service';
import { LeaveResourceService } from './leaveResource.service';
export * from './reportStatusResource.service';
import { ReportStatusResourceService } from './reportStatusResource.service';
export * from './userDataBeanResource.service';
import { UserDataBeanResourceService } from './userDataBeanResource.service';
export * from './userExtraResource.service';
import { UserExtraResourceService } from './userExtraResource.service';
export * from './userJwtController.service';
import { UserJwtControllerService } from './userJwtController.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export const APIS = [AccountResourceService, AppraisalControllerResourceService, AppraisalResourceService, GitResourceService, HackathonResourceService, JiraResourceService, LateArrivalResourceService, LeaveResourceService, ReportStatusResourceService, UserDataBeanResourceService, UserExtraResourceService, UserJwtControllerService, UserResourceService];
