/**
 * appraisal API
 * appraisal API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserExtra } from './userExtra';


export interface Appraisal { 
    attendance?: number;
    codeQuality?: number;
    companyPolicy?: number;
    date?: string;
    id?: number;
    meetingTargets?: number;
    punctuality?: number;
    userExtra?: UserExtra;
}

