/**
 * appraisal API
 * appraisal API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ManagedUserVM { 
    activated?: boolean;
    authorities?: Array<string>;
    company?: string;
    createdBy?: string;
    createdDate?: string;
    dob?: string;
    email?: string;
    firstName?: string;
    id?: number;
    image?: string;
    imageContentType?: string;
    imageUrl?: string;
    joiningDate?: string;
    langKey?: string;
    lastModifiedBy?: string;
    lastModifiedDate?: string;
    lastName?: string;
    login?: string;
    password?: string;
    position?: string;
    username?: string;
}

