/**
 * appraisal API
 * appraisal API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Git } from './git';
import { User } from './user';
import { LateArrival } from './lateArrival';
import { Leave } from './leave';
import { Appraisal } from './appraisal';
import { ReportStatus } from './reportStatus';
import { Hackathon } from './hackathon';


export interface UserExtra { 
    appraisals?: Array<Appraisal>;
    company?: string;
    dob?: string;
    gits?: Array<Git>;
    hackathons?: Array<Hackathon>;
    id?: number;
    image?: string;
    imageContentType?: string;
    joiningDate?: string;
    lateArrivals?: Array<LateArrival>;
    leaves?: Array<Leave>;
    position?: string;
    reportStatuses?: Array<ReportStatus>;
    user?: User;
    username?: string;
}

