/**
 * appraisal API
 * appraisal API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDataBean { 
    attendance?: number;
    codeQuality?: number;
    company?: string;
    companyPolicy?: number;
    email?: string;
    firstName?: string;
    id?: number;
    lastName?: string;
    meetingTargets?: number;
    position?: string;
    punctuality?: number;
}

