/**
 * appraisal API
 * appraisal API documentation
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Authority } from './authority';


export interface UserExtraDTO { 
    authorities?: Array<Authority>;
    company?: string;
    dob?: string;
    email?: string;
    firstName?: string;
    id?: number;
    image?: string;
    imageContentType?: string;
    joiningDate?: string;
    lastName?: string;
    login?: string;
    position?: string;
}

